#Copied from TinityCore.
#Editied to match our environment.

sudo: required
dist: trusty

language: cpp
compiler:
  - g++

git:
  depth: 1

before_install:
  - sudo apt-get -qq install build-essential libtool make cmake cmake-data openssl
  - sudo apt-get -qq install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev
  - sudo apt-get -qq install libboost1.55-dev libboost-thread1.55-dev libboost-filesystem1.55-dev libboost-system1.55-dev libboost-program-options1.55-dev libboost-iostreams1.55-dev libboost-regex1.55-dev
  - sudo apt-get -qq install libace-dev
  - sudo apt-get -qq install libtbb-dev
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - mkdir bin
  - cd bin
  - cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS="dynamic" -DSERVERS=1 -DNOJEM=1 -DWITH_DYNAMIC_LINKING=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-w" -DCMAKE_CXX_FLAGS="-w" -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..

script:
  - $CXX --version
  - cd bin
  - make -j 8 -k && make install
