-- High Warlord Naj'entus script texts updates

-- Delete all existing script texts
DELETE FROM `script_texts` WHERE `entry` IN (-1564000, -1564001, -1564002, -1564003, -1564004, -1564005, -1564006, -1564007, -1564008, -1564009);

-- Insert updated script texts
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1564000, 'You will die in the name of Lady Vashj!', NULL, NULL, 'Im Namen Lady Vashj\'s werdet ihr sterben!', NULL, NULL, NULL, NULL, NULL, 11450, 6, 0, 0, 'SAY_AGGRO');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1564001, 'Stick around...', NULL, NULL, 'Bleibt doch noch!', NULL, NULL, NULL, NULL, NULL, 11451, 6, 0, 0, 'SAY_NEEDLE1');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1564002, 'I\'ll deal with you later.', NULL, NULL, 'Um euch kümmere ich mich später!', NULL, NULL, NULL, NULL, NULL, 11452, 6, 0, 0, 'SAY_NEEDLE2');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1564003, 'Your success was short-lived!', NULL, NULL, 'Euer Erfolg war von kurzer Dauer!', NULL, NULL, NULL, NULL, NULL, 11455, 6, 0, 0, 'SAY_SLAY1');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1564004, 'Time for you to go.', NULL, NULL, 'Zeit für euch zu gehen!', NULL, NULL, NULL, NULL, NULL, 11456, 6, 0, 0, 'SAY_SLAY2');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1564005, 'Be\'lanen dalorei!', NULL, NULL, 'Be\'lanen dalorei!', NULL, NULL, NULL, NULL, NULL, 11453, 6, 0, 0, 'SAY_SPECIAL1');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1564006, 'Blood... will... flow!', NULL, NULL, 'Blut soll fließen!', NULL, NULL, NULL, NULL, NULL, 11454, 6, 0, 0, 'SAY_SPECIAL2');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1564007, 'Bal, lamer zhita!', NULL, NULL, 'Bal\'amer ch\'itah!', NULL, NULL, NULL, NULL, NULL, 11457, 6, 0, 0, 'SAY_ENRAGE1');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1564008, 'My patience has run out! Die! Die!', NULL, NULL, 'Meine Geduld ist erschöpft! Sterbt, STERBT!', NULL, NULL, NULL, NULL, NULL, 11458, 6, 0, 0, 'SAY_ENRAGE2');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1564009, 'Lord Illidan will... crush you!', NULL, NULL, 'Fürst Illidan wird euch... zermalmen.', NULL, NULL, NULL, NULL, NULL, 11459, 6, 0, 0, 'SAY_DEATH');
